name: redis
icon: redis
type: datastore
title: Redis
options:
- version: '8.6'
  tag: '8.6'
- version: '8.4'
  tag: '8.4'
- version: '8.2'
  tag: '8.2'
- version: '8.0'
  tag: '8.0'
  eol: '2026-02-11T00:00:00+00:00'
endpoints:
- name: redis
  ports:
  - name: redis
    number: 6379
    protocol: tcp
labels:
- redis

volumes:
- name: data
  title: Data
  optional: true
  helm:
# @todo: remove labels if imports introduced  
    labels: persistence.labels
    values:
    - name: persistence.enabled
      value: true
    - name: persistence.size
      value: '{{volumes.data.size}}Gi'
    # mandatory to use existing claim since this volume will have import function
    # we will mount different claim after import and doing it through sts's volumeclaimtemplates is not supported
# disabled due to missing imports (required for this to work – we create PVC manually instead of using volumeClaimTemplate)
# @todo: remove labels if imports introduced
#    - name: persistence.existingClaim
#      value: '{{volumes.data.claim}}'

tokens:
- name: password
  generate:
    regex: '[0-9a-z-]{32}'

helm:
  name: wodby
  source: oci://registry-1.docker.io/wodby/redis
  chart: oci://registry-1.docker.io/wodby/redis
  version: 0.1.0
  values:
  - name: auth.password
    value: '{{password}}'

workloads:
- id: main
  kind: statefulset
  primary: true
  helm:
    labels: podLabels
    annotations: podAnnotations
    volumes: extraVolumes
  containers:
  - name: redis
    image: wodby/redis
    helm:
      resources: resources
      env: envVars
      mounts: extraVolumeMounts
