apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    name: redis
  name: redis
spec:
  serviceName: redis
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
      - image: wodby/redis
        name: redis
        ports:
        - containerPort: 6379
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - make
            - check-ready
            - -f
            - /usr/local/bin/actions.mk
          failureThreshold: 3
          initialDelaySeconds: 20
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 3

